### ISSUE TITLE
Font Awesome

### ISSUE THREAD

**Issue by scragg0x** [react-component/menu#100]
I noticed that FontAwesome was included starting in 5.1.  From what I understand, it used for the submenu arrows.  I wanted to propose a prop to disable the arrows and a have a separate css file that does not include FA.  

I also think it would be best as peer dependency since it will give the dev flexibility to load a single instance of font-awesome on whatever version they see fit.

Let me know what you think, thanks for the hard work.

**Comment by benjycui** [comment]
Just override the CSS, thanks. We don't want to maintain two CSS files.

**Comment by scragg0x** [comment]
Can't override this afiak

```css
@font-face {
  font-family: 'FontAwesome';
  src: url('https://cdn.bootcss.com/font-awesome/4.2.0/fonts/fontawesome-webfont.eot?v=4.2.0');
  src: url('https://cdn.bootcss.com/font-awesome/4.2.0/fonts/fontawesome-webfont.eot?#iefix&v=4.2.0') format('embedded-opentype'), url('https://cdn.bootcss.com/font-awesome/4.2.0/fonts/fontawesome-webfont.woff?v=4.2.0') format('woff'), url('https://cdn.bootcss.com/font-awesome/4.2.0/fonts/fontawesome-webfont.ttf?v=4.2.0') format('truetype'), url('https://cdn.bootcss.com/font-awesome/4.2.0/fonts/fontawesome-webfont.svg?v=4.2.0#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```
