### ISSUE TITLE
Horizontal menu does not overflow if preceded by a floating block

### ISSUE THREAD

**Issue by yp** [react-component/menu#200]
I am recreating a layout similar to that of https://ant.design/components/layout/#components-layout-demo-top but placing a logo on the left of the menu apparently breaks the computation of the menu width and, hence, of the overflowed items.

![error](https://user-images.githubusercontent.com/275483/45819231-238feb80-bce4-11e8-84db-9faa7a7c9ca3.png)

````jsx
import React from 'react';

import { Layout, Menu } from 'antd';

const { Header } = Layout;

function App(props) {
  return (
    <Layout>
      <Header>
        <div className="logo" />
        <Menu
          theme="dark"
          mode="horizontal"
          defaultSelectedKeys={['2']}
          style={{ lineHeight: '64px', fontSize: '125%' }}
        >
          <Menu.Item key="1">menu 1</Menu.Item>
          <Menu.Item key="2">menu 2</Menu.Item>
          <Menu.Item key="3">menu 3</Menu.Item>
        </Menu>
      </Header>
    </Layout>
  );
}
````

````css
.logo {
  width: 186px;
  height: 48px;
  background-color: red;
  margin: 8px 24px 8px 0;
  float: left;
}
````
